[id]
name = splunk-agent-mesh
version = 0.1.0

[ui]
is_visible = 1
label = Splunk Agent Mesh
supported_themes = light,dark

[launcher]
author = Splunk
description = Splunk Agent Mesh
version = 0.1.0

[package]
check_for_updates = 0
id = splunk-agent-mesh

[install]
is_configured = 1
build = 1

[triggers]
reload.splunk_create = simple